export const mockData = {
  config: {
    data_length: 24,
    eng_market: "all",
    month: 8,
    period: "monthly",
    period_length: 6,
    region: "all",
    share_type: "total",
    view: "L3",
    year: 2024,
  },
  data: [
    {
      date: "Wed, 31 Jan 2024 00:00:00 GMT",
      eng_market: "CINCINNATI",
      month: 1,
      period: "JAN'24",
      post_att_share: 30.0,
      post_other_share: 20.0,
      post_tmus_share: 18.0,
      post_verizon_share: 32.0,
      pre_att_share: 28.0,
      pre_other_share: 22.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "CENTRAL",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 22.0,
      total_verizon_share: 28.0,
      year: 2024,
    },
    {
      date: "Thu, 29 Feb 2024 00:00:00 GMT",
      eng_market: "CINCINNATI",
      month: 2,
      period: "FEB'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 22.0,
      post_verizon_share: 28.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 23.0,
      pre_verizon_share: 27.0,
      quarter: null,
      region: "CENTRAL",
      total_att_share: 27.0,
      total_other_share: 23.0,
      total_tmus_share: 24.0,
      total_verizon_share: 26.0,
      year: 2024,
    },
    {
      date: "Sun, 31 Mar 2024 00:00:00 GMT",
      eng_market: "CINCINNATI",
      month: 3,
      period: "MAR'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 20.0,
      post_verizon_share: 30.0,
      pre_att_share: 24.0,
      pre_other_share: 26.0,
      pre_tmus_share: 26.0,
      pre_verizon_share: 24.0,
      quarter: null,
      region: "CENTRAL",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 25.0,
      total_verizon_share: 25.0,
      year: 2024,
    },
    {
      date: "Tue, 30 Apr 2024 00:00:00 GMT",
      eng_market: "CINCINNATI",
      month: 4,
      period: "APR'24",
      post_att_share: 24.0,
      post_other_share: 26.0,
      post_tmus_share: 22.0,
      post_verizon_share: 28.0,
      pre_att_share: 23.0,
      pre_other_share: 27.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "CENTRAL",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 20.0,
      total_verizon_share: 30.0,
      year: 2024,
    },
    {
      date: "Fri, 31 May 2024 00:00:00 GMT",
      eng_market: "CINCINNATI",
      month: 5,
      period: "MAY'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 25.0,
      post_verizon_share: 25.0,
      pre_att_share: 24.0,
      pre_other_share: 26.0,
      pre_tmus_share: 23.0,
      pre_verizon_share: 27.0,
      quarter: null,
      region: "CENTRAL",
      total_att_share: 26.0,
      total_other_share: 24.0,
      total_tmus_share: 21.0,
      total_verizon_share: 29.0,
      year: 2024,
    },
    {
      date: "Sun, 30 Jun 2024 00:00:00 GMT",
      eng_market: "CINCINNATI",
      month: 6,
      period: "JUN'24",
      post_att_share: 26.0,
      post_other_share: 24.0,
      post_tmus_share: 24.0,
      post_verizon_share: 26.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 25.0,
      pre_verizon_share: 25.0,
      quarter: null,
      region: "CENTRAL",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 23.0,
      total_verizon_share: 27.0,
      year: 2024,
    },
    {
      date: "Wed, 31 Jan 2024 00:00:00 GMT",
      eng_market: "DALLAS",
      month: 1,
      period: "JAN'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 22.0,
      post_verizon_share: 28.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 25.0,
      pre_verizon_share: 25.0,
      quarter: null,
      region: "SOUTH",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 20.0,
      total_verizon_share: 30.0,
      year: 2024,
    },
    {
      date: "Thu, 29 Feb 2024 00:00:00 GMT",
      eng_market: "DALLAS",
      month: 2,
      period: "FEB'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 25.0,
      post_verizon_share: 25.0,
      pre_att_share: 24.0,
      pre_other_share: 26.0,
      pre_tmus_share: 22.0,
      pre_verizon_share: 28.0,
      quarter: null,
      region: "SOUTH",
      total_att_share: 24.0,
      total_other_share: 26.0,
      total_tmus_share: 20.0,
      total_verizon_share: 30.0,
      year: 2024,
    },
    {
      date: "Sun, 31 Mar 2024 00:00:00 GMT",
      eng_market: "DALLAS",
      month: 3,
      period: "MAR'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 21.0,
      post_verizon_share: 29.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 25.0,
      pre_verizon_share: 25.0,
      quarter: null,
      region: "SOUTH",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 22.0,
      total_verizon_share: 28.0,
      year: 2024,
    },
    {
      date: "Tue, 30 Apr 2024 00:00:00 GMT",
      eng_market: "DALLAS",
      month: 4,
      period: "APR'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 21.0,
      post_verizon_share: 29.0,
      pre_att_share: 26.0,
      pre_other_share: 24.0,
      pre_tmus_share: 26.0,
      pre_verizon_share: 24.0,
      quarter: null,
      region: "SOUTH",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 23.0,
      total_verizon_share: 27.0,
      year: 2024,
    },
    {
      date: "Fri, 31 May 2024 00:00:00 GMT",
      eng_market: "DALLAS",
      month: 5,
      period: "MAY'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 20.0,
      post_verizon_share: 30.0,
      pre_att_share: 24.0,
      pre_other_share: 26.0,
      pre_tmus_share: 22.0,
      pre_verizon_share: 28.0,
      quarter: null,
      region: "SOUTH",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 20.0,
      total_verizon_share: 30.0,
      year: 2024,
    },
    {
      date: "Sun, 30 Jun 2024 00:00:00 GMT",
      eng_market: "DALLAS",
      month: 6,
      period: "JUN'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 20.0,
      post_verizon_share: 30.0,
      pre_att_share: 24.0,
      pre_other_share: 26.0,
      pre_tmus_share: 22.0,
      pre_verizon_share: 28.0,
      quarter: null,
      region: "SOUTH",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 25.0,
      total_verizon_share: 25.0,
      year: 2024,
    },
    {
      date: "Wed, 31 Jan 2024 00:00:00 GMT",
      eng_market: "LAS VEGAS",
      month: 1,
      period: "JAN'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 20.0,
      post_verizon_share: 30.0,
      pre_att_share: 26.0,
      pre_other_share: 26.0,
      pre_tmus_share: 22.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "WEST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 23.0,
      total_verizon_share: 27.0,
      year: 2024,
    },
    {
      date: "Thu, 29 Feb 2024 00:00:00 GMT",
      eng_market: "LAS VEGAS",
      month: 2,
      period: "FEB'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 22.0,
      post_verizon_share: 28.0,
      pre_att_share: 26.0,
      pre_other_share: 24.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "WEST",
      total_att_share: 27.0,
      total_other_share: 23.0,
      total_tmus_share: 21.0,
      total_verizon_share: 29.0,
      year: 2024,
    },
    {
      date: "Sun, 31 Mar 2024 00:00:00 GMT",
      eng_market: "LAS VEGAS",
      month: 3,
      period: "MAR'24",
      post_att_share: 26.0,
      post_other_share: 24.0,
      post_tmus_share: 24.0,
      post_verizon_share: 26.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 22.0,
      pre_verizon_share: 28.0,
      quarter: null,
      region: "WEST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 20.0,
      total_verizon_share: 30.0,
      year: 2024,
    },
    {
      date: "Tue, 30 Apr 2024 00:00:00 GMT",
      eng_market: "LAS VEGAS",
      month: 4,
      period: "APR'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 23.0,
      post_verizon_share: 27.0,
      pre_att_share: 20.0,
      pre_other_share: 30.0,
      pre_tmus_share: 25.0,
      pre_verizon_share: 25.0,
      quarter: null,
      region: "WEST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 25.0,
      total_verizon_share: 25.0,
      year: 2024,
    },
    {
      date: "Fri, 31 May 2024 00:00:00 GMT",
      eng_market: "LAS VEGAS",
      month: 5,
      period: "MAY'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 22.0,
      post_verizon_share: 28.0,
      pre_att_share: 26.0,
      pre_other_share: 24.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "WEST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 23.0,
      total_verizon_share: 27.0,
      year: 2024,
    },
    {
      date: "Sun, 30 Jun 2024 00:00:00 GMT",
      eng_market: "LAS VEGAS",
      month: 6,
      period: "JUN'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 23.0,
      post_verizon_share: 27.0,
      pre_att_share: 26.0,
      pre_other_share: 24.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "WEST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 22.0,
      total_verizon_share: 28.0,
      year: 2024,
    },
    {
      date: "Wed, 31 Jan 2024 00:00:00 GMT",
      eng_market: "PHILADELPHIA",
      month: 1,
      period: "JAN'24",
      post_att_share: 27.0,
      post_other_share: 23.0,
      post_tmus_share: 21.0,
      post_verizon_share: 29.0,
      pre_att_share: 26.0,
      pre_other_share: 24.0,
      pre_tmus_share: 23.0,
      pre_verizon_share: 27.0,
      quarter: null,
      region: "NORTHEAST",
      total_att_share: 26.0,
      total_other_share: 24.0,
      total_tmus_share: 21.0,
      total_verizon_share: 29.0,
      year: 2024,
    },
    {
      date: "Thu, 29 Feb 2024 00:00:00 GMT",
      eng_market: "PHILADELPHIA",
      month: 2,
      period: "FEB'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 23.0,
      post_verizon_share: 27.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "NORTHEAST",
      total_att_share: 26.0,
      total_other_share: 24.0,
      total_tmus_share: 22.0,
      total_verizon_share: 28.0,
      year: 2024,
    },
    {
      date: "Sun, 31 Mar 2024 00:00:00 GMT",
      eng_market: "PHILADELPHIA",
      month: 3,
      period: "MAR'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 23.0,
      post_verizon_share: 27.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "NORTHEAST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 23.0,
      total_verizon_share: 27.0,
      year: 2024,
    },
    {
      date: "Tue, 30 Apr 2024 00:00:00 GMT",
      eng_market: "PHILADELPHIA",
      month: 4,
      period: "APR'24",
      post_att_share: 27.0,
      post_other_share: 23.0,
      post_tmus_share: 20.0,
      post_verizon_share: 30.0,
      pre_att_share: 26.0,
      pre_other_share: 24.0,
      pre_tmus_share: 22.0,
      pre_verizon_share: 28.0,
      quarter: null,
      region: "NORTHEAST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 24.0,
      total_verizon_share: 26.0,
      year: 2024,
    },
    {
      date: "Fri, 31 May 2024 00:00:00 GMT",
      eng_market: "PHILADELPHIA",
      month: 5,
      period: "MAY'24",
      post_att_share: 26.0,
      post_other_share: 24.0,
      post_tmus_share: 24.0,
      post_verizon_share: 26.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 25.0,
      pre_verizon_share: 25.0,
      quarter: null,
      region: "NORTHEAST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 22.0,
      total_verizon_share: 28.0,
      year: 2024,
    },
    {
      date: "Sun, 30 Jun 2024 00:00:00 GMT",
      eng_market: "PHILADELPHIA",
      month: 6,
      period: "JUN'24",
      post_att_share: 25.0,
      post_other_share: 25.0,
      post_tmus_share: 23.0,
      post_verizon_share: 27.0,
      pre_att_share: 25.0,
      pre_other_share: 25.0,
      pre_tmus_share: 24.0,
      pre_verizon_share: 26.0,
      quarter: null,
      region: "NORTHEAST",
      total_att_share: 25.0,
      total_other_share: 25.0,
      total_tmus_share: 24.0,
      total_verizon_share: 26.0,
      year: 2024,
    },
  ],
};
